// File generated by FlutterFire CLI — replace values with your project.
// Run from this app folder:
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// Until configured, replace the placeholder strings below with values from
// Firebase Console → Project settings → Your apps.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return windows;
      default:
        return macos;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMLig3y06RxZos0A2hnnmGZe4fkDq8cUk',
    appId: '1:570598256259:web:0b3f31c4e68bbad21475b6',
    messagingSenderId: '570598256259',
    projectId: 'devclaypos',
    authDomain: 'devclaypos.firebaseapp.com',
    storageBucket: 'devclaypos.firebasestorage.app',
    measurementId: 'G-FCJ7R371VJ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl-3o_6ZroHDU5BUTfVnT3S98HbJUNZQE',
    appId: '1:570598256259:ios:15f1794832e994171475b6',
    messagingSenderId: '570598256259',
    projectId: 'devclaypos',
    storageBucket: 'devclaypos.firebasestorage.app',
    iosBundleId: 'com.example.devclayPosSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMLig3y06RxZos0A2hnnmGZe4fkDq8cUk',
    appId: '1:570598256259:web:912448889dff68921475b6',
    messagingSenderId: '570598256259',
    projectId: 'devclaypos',
    authDomain: 'devclaypos.firebaseapp.com',
    storageBucket: 'devclaypos.firebasestorage.app',
    measurementId: 'G-K7D546ZEWG',
  );
}
