// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMLig3y06RxZos0A2hnnmGZe4fkDq8cUk',
    appId: '1:570598256259:web:0b3f31c4e68bbad21475b6',
    messagingSenderId: '570598256259',
    projectId: 'devclaypos',
    authDomain: 'devclaypos.firebaseapp.com',
    storageBucket: 'devclaypos.firebasestorage.app',
    measurementId: 'G-FCJ7R371VJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMFWKKbyszmFWTh3S-EH6DC9Gl7Sgu5IY',
    appId: '1:570598256259:android:c905682139bb945a1475b6',
    messagingSenderId: '570598256259',
    projectId: 'devclaypos',
    storageBucket: 'devclaypos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl-3o_6ZroHDU5BUTfVnT3S98HbJUNZQE',
    appId: '1:570598256259:ios:a0c7946b40b91ba91475b6',
    messagingSenderId: '570598256259',
    projectId: 'devclaypos',
    storageBucket: 'devclaypos.firebasestorage.app',
    iosBundleId: 'com.example.devclayPosAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl-3o_6ZroHDU5BUTfVnT3S98HbJUNZQE',
    appId: '1:570598256259:ios:a0c7946b40b91ba91475b6',
    messagingSenderId: '570598256259',
    projectId: 'devclaypos',
    storageBucket: 'devclaypos.firebasestorage.app',
    iosBundleId: 'com.example.devclayPosAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMLig3y06RxZos0A2hnnmGZe4fkDq8cUk',
    appId: '1:570598256259:web:8339ac27ca8269f61475b6',
    messagingSenderId: '570598256259',
    projectId: 'devclaypos',
    authDomain: 'devclaypos.firebaseapp.com',
    storageBucket: 'devclaypos.firebasestorage.app',
    measurementId: 'G-P59L83JFL4',
  );
}
